// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/app/logic.go
//
// Generated by this command:
//
//	mockgen -source=internal/user/app/logic.go -destination=internal/user/app/logic_mock.go -package=app
//

// Package app is a generated GoMock package.
package app
